install: mvn clean install

language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "2a31a4ab981e7e4dce32a452d9683677d4ff58fa"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=com.sandboni.core:sandboni-core