language: java
jdk:
  - openjdk8

install: true

stages:
  - name: release
    if: branch = master and type = pull_request and repo = jpmorganchase/sandboni-core
  - name: pull request
    if: type = pull_request OR type = push AND branch != master

jobs:
  include:
    - stage: release
      name: "Release: mvn clean deploy"
      script:
        - mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease

    - stage: pull request
      name: "Pull Request: mvn clean package sonar:sonar"
      script:
        - mvn clean install sonar:sonar -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file:
    - sandboni-engine/target/sandboni-engine-$project_version.jar
    - sandboni-scm/target/sandboni-scm-$project_version.jar
  skip_cleanup: true
  on:
    repo: jpmorganchase/sandboni-core
  name: $project_version

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'