language: java
jdk:
  - openjdk8

install: true

#stages:
#  - name: release
#    if: branch = master AND type = pull_request AND repo = jpmorganchase/sandboni-core AND head_branch = develop
#  - name: pull request
#    if: type IN (push, pull_request, cron)

stages:
  - name: release
    if: repo = jpmorganchase/sandboni-core AND branch = master AND AND head_branch = develop AND type = pull_request
  - name: pull request
    if: type IN (push, pull_request, cron)

jobs:
  include:
    - stage: release
      name: "Develop -> Master release: mvn clean deploy"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      before_deploy:
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
      script:
        - mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        file:
          - engine/target/sandboni-engine-$project_version.jar
          - scm/target/sandboni-scm-$project_version.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
        name: $project_version

    - stage: pull request
      name: "Any Pull Request: mvn clean package sonar:sonar"
      script:
        - mvn clean install sonar:sonar

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'