dist: trusty
language: java
jdk: openjdk8
install: true

jobs:
  include:
    - stage: sonar
      if: repo = jpmorganchase/sandboni-core
      name: "PR: mvn clean verify sonar:sonar"
      script:
        - mvn clean verify sonar:sonar
      after_success:
        - source ./scripts/breakbuild.sh

    - stage: release
      if: repo = jpmorganchase/sandboni-core AND head_repo = jpmorganchase/sandboni-core AND branch = release AND head_branch = master
      name: "Release: Tag on GitHub and deploy to OSSRH"
      script:
        - source ./scripts/release.sh

    - stage: snapshot release
      if: repo = jpmorganchase/sandboni-core AND head_repo = jpmorganchase/sandboni-core AND branch = master AND head_branch = develop
      name: "SNAPSHOT release"
      script:
        - source ./scripts/snapshotRelease.sh
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        file:
          - target/sandboni-*.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
          tags: true

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'