dist: trusty
language: java
jdk: openjdk8
install: true

jobs:
  include:
    - stage: sonar
      if: repo = jpmorganchase/sandboni-core
      name: "Any push or pull request"
      script:
        - mvn clean install sonar:sonar
      after_success:
        - source ./scripts/breakbuild.sh

    - stage: release
      if: repo = jpmorganchase/sandboni-core #AND branch = master AND head_branch = develop AND type = pull_request
      name: "Develop -> Master release: mvn clean deploy"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      before_deploy:
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
      install:
        - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean deploy -DskipTests=true --settings .maven.xml -B -U -Prelease
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        file:
          - target/sandboni-*.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
          tags: true
        name: $project_version

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'