dist: trusty
language: java
jdk: openjdk8
install: true

jobs:
  include:
#    - stage: sonar
#      if: repo = jpmorganchase/sandboni-core
#      name: "Any push or pull request"
#      script:
#        - mvn clean verify sonar:sonar
#      after_success:
#        - source ./scripts/breakbuild.sh

    - stage: release
      if: repo = jpmorganchase/sandboni-core #AND branch = master AND head_branch = develop AND type = pull_request
      name: "Develop -> Master release: mvn clean deploy"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
#      before_deploy:
#        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        script: source ./scripts/release.sh
        file:
          - target/sandboni-*.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
          tags: true
          jdk: openjdk8

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'