language: java
jdk: openjdk8
install: true

jobs:
  include:
    - stage: release
      if: repo = jpmorganchase/sandboni-core AND branch = master AND head_branch = develop AND type = pull_request
      name: "Develop -> Master release: mvn clean deploy"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      before_deploy:
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
      script:
        - mvn clean deploy -DskipTests=true --settings .maven.xml -B -U -Prelease
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        file:
          - engine/target/sandboni-engine-$project_version.jar
          - scm/target/sandboni-scm-$project_version.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
        name: $project_version

    - stage: sonar
      name: "Any push or pull request"
      script:
        - mvn clean install sonar:sonar
      after_success:
        - echo "Running after_success stage"
        - chmod +x ./ci/breakbuild.sh



addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'