dist: trusty
language: java
jdk: openjdk8
install: true

jobs:
  include:
    - stage: sonar
      if: repo = jpmorganchase/sandboni-core
      name: "PR: mvn clean verify sonar:sonar"
      script:
        - mvn clean verify sonar:sonar
      after_success:
        - source ./scripts/breakbuild.sh

    - stage: release
      if: repo = jpmorganchase/sandboni-core AND branch = master AND type = push
      name: "Release: Tag on GitHub and deploy to OSSRH"
      script:
        - source ./scripts/release.sh

    - stage: snapshot release
      if: repo = jpmorganchase/sandboni-core AND branch = develop AND type = push
      name: "SNAPSHOT release"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      before_deploy:
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
      script:
        - mvn clean deploy -DskipTests=true --settings .maven.xml -B -U -Prelease
      deploy:
        provider: releases
        api_key:
          secure: "$GITHUB_TOKEN"
        file:
          - target/sandboni-*.jar
        skip_cleanup: true
        on:
          repo: jpmorganchase/sandboni-core
          tags: true

addons:
  sonarcloud:
    organization: "sandboni"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'